version: '3.8'

services:
  mysql:
    build:
      context: ./MySQL
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cat
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - service

  backend:
    build:
      context: ./Go
    command: bash -c 'sleep 60; ./main'
    expose:
      - "8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    depends_on:
      - mysql
    networks:
      - service

  nginx:
    build:
      context: ./Nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - service

networks:
  service:
    driver: bridge

volumes:
  mysql-data:
