global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
receivers:
- name: 'email-notify'
  email_configs:
  - to: 'sherry910509@gmail.com'
    send_resolved: true
inhibit_rules:
- source_match:
  severity: 'critical'
target_match:
  severity: 'warning'
equal: ['alertname', 'instance']
