route:
  receiver: "gmail-notifications"
receivers:
  - name: "gmail-notifications"
    email_configs:
      - to: sherry910509@gmail.com
        from: sherry910509@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: sherry910509@gmail.com
        auth_identity: sherry910509@gmail.com
        auth_password: ijox jecz tdit cipc
        send_resolved: true