services:
  server:
    build:
      context: ./server
    networks:
      - chat

  client:
    build:
      context: ./client
    depends_on:
      - server
    networks:
      - chat

networks:
  chat:
    driver: bridge
