global:
  scrape_interval: 10s
rule_files:
  - alert.yml
scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["localhost:8080"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"